version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mushroomapp
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
    env_file:
      - .env


  db:
    image: postgres
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:

networks:
  default:
    name: ‘mynetwork’